services:

  backend:
    build: ./backend
    container_name: statrush_backend
    ports:
      - "5001:5000"

  frontend:
    build: ./frontend
    container_name: statrush_frontend
    ports:
      - "3001:5173"
    depends_on:
      - backend